use crate::providers::ProviderKind;
use serde::{Deserialize, Serialize};

/// Describes a single editable field for the dynamic UI.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FieldDef {
    /// Internal key name (stored in DB)
    pub key: String,
    /// Human-readable label for the UI
    pub label: String,
    /// Field type: "string", "number", "boolean", "date", "url", "text" (multiline),
    /// "rating", "json", "select", "tags"
    pub field_type: String,
    /// Category/group for organizing in the UI: "core", "metadata", "status", "api_specific"
    pub group: String,
    /// Whether this field is editable by the user
    pub editable: bool,
    /// Whether this field should be displayed in the detail view
    pub visible: bool,
    /// Sort order within its group
    pub order: i32,
    /// Optional: For "select" type, the list of allowed values
    #[serde(skip_serializing_if = "Option::is_none")]
    pub options: Option<Vec<String>>,
    /// Optional: placeholder or help text
    #[serde(skip_serializing_if = "Option::is_none")]
    pub placeholder: Option<String>,
}

/// Schema for a given provider + item type combination
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FieldSchema {
    pub provider_id: ProviderKind,
    pub provider_name: String,
    /// "book" or "series"
    pub item_type: String,
    pub fields: Vec<FieldDef>,
}

/// Returns the common fields shared by ALL providers for books.
pub fn common_book_fields() -> Vec<FieldDef> {
    vec![
        FieldDef {
            key: "title".into(),
            label: "Title".into(),
            field_type: "string".into(),
            group: "core".into(),
            editable: true,
            visible: true,
            order: 1,
            options: None,
            placeholder: None,
        },
        FieldDef {
            key: "path".into(),
            label: "File Path".into(),
            field_type: "string".into(),
            group: "core".into(),
            editable: true,
            visible: true,
            order: 2,
            options: None,
            placeholder: Some("Path to the comic file".into()),
        },
        FieldDef {
            key: "cover_url".into(),
            label: "Cover URL".into(),
            field_type: "url".into(),
            group: "core".into(),
            editable: true,
            visible: true,
            order: 3,
            options: None,
            placeholder: None,
        },
        FieldDef {
            key: "description".into(),
            label: "Description".into(),
            field_type: "text".into(),
            group: "core".into(),
            editable: true,
            visible: true,
            order: 4,
            options: None,
            placeholder: None,
        },
        FieldDef {
            key: "issue_number".into(),
            label: "Issue Number".into(),
            field_type: "string".into(),
            group: "metadata".into(),
            editable: true,
            visible: true,
            order: 10,
            options: None,
            placeholder: None,
        },
        FieldDef {
            key: "format".into(),
            label: "Format".into(),
            field_type: "string".into(),
            group: "metadata".into(),
            editable: true,
            visible: true,
            order: 11,
            options: None,
            placeholder: Some("Comic, Trade Paperback, Manga, etc.".into()),
        },
        FieldDef {
            key: "page_count".into(),
            label: "Page Count".into(),
            field_type: "number".into(),
            group: "metadata".into(),
            editable: true,
            visible: true,
            order: 12,
            options: None,
            placeholder: None,
        },
        FieldDef {
            key: "creators".into(),
            label: "Creators".into(),
            field_type: "tags".into(),
            group: "metadata".into(),
            editable: true,
            visible: true,
            order: 13,
            options: None,
            placeholder: None,
        },
        FieldDef {
            key: "characters".into(),
            label: "Characters".into(),
            field_type: "tags".into(),
            group: "metadata".into(),
            editable: true,
            visible: true,
            order: 14,
            options: None,
            placeholder: None,
        },
        // Status fields
        FieldDef {
            key: "read".into(),
            label: "Read".into(),
            field_type: "boolean".into(),
            group: "status".into(),
            editable: true,
            visible: true,
            order: 20,
            options: None,
            placeholder: None,
        },
        FieldDef {
            key: "reading".into(),
            label: "Reading".into(),
            field_type: "boolean".into(),
            group: "status".into(),
            editable: true,
            visible: true,
            order: 21,
            options: None,
            placeholder: None,
        },
        FieldDef {
            key: "unread".into(),
            label: "Unread".into(),
            field_type: "boolean".into(),
            group: "status".into(),
            editable: true,
            visible: true,
            order: 22,
            options: None,
            placeholder: None,
        },
        FieldDef {
            key: "favorite".into(),
            label: "Favorite".into(),
            field_type: "boolean".into(),
            group: "status".into(),
            editable: true,
            visible: true,
            order: 23,
            options: None,
            placeholder: None,
        },
        FieldDef {
            key: "note".into(),
            label: "Rating".into(),
            field_type: "rating".into(),
            group: "status".into(),
            editable: true,
            visible: true,
            order: 24,
            options: None,
            placeholder: None,
        },
        FieldDef {
            key: "last_page".into(),
            label: "Last Page Read".into(),
            field_type: "number".into(),
            group: "status".into(),
            editable: true,
            visible: true,
            order: 25,
            options: None,
            placeholder: None,
        },
        FieldDef {
            key: "lock".into(),
            label: "Lock Metadata".into(),
            field_type: "boolean".into(),
            group: "status".into(),
            editable: true,
            visible: true,
            order: 26,
            options: None,
            placeholder: None,
        },
    ]
}

/// Returns the common fields shared by ALL providers for series.
pub fn common_series_fields() -> Vec<FieldDef> {
    vec![
        FieldDef {
            key: "title".into(),
            label: "Title".into(),
            field_type: "string".into(),
            group: "core".into(),
            editable: true,
            visible: true,
            order: 1,
            options: None,
            placeholder: None,
        },
        FieldDef {
            key: "path".into(),
            label: "Folder Path".into(),
            field_type: "string".into(),
            group: "core".into(),
            editable: true,
            visible: true,
            order: 2,
            options: None,
            placeholder: None,
        },
        FieldDef {
            key: "cover_url".into(),
            label: "Cover URL".into(),
            field_type: "url".into(),
            group: "core".into(),
            editable: true,
            visible: true,
            order: 3,
            options: None,
            placeholder: None,
        },
        FieldDef {
            key: "bg_url".into(),
            label: "Background URL".into(),
            field_type: "url".into(),
            group: "core".into(),
            editable: true,
            visible: true,
            order: 4,
            options: None,
            placeholder: None,
        },
        FieldDef {
            key: "description".into(),
            label: "Description".into(),
            field_type: "text".into(),
            group: "core".into(),
            editable: true,
            visible: true,
            order: 5,
            options: None,
            placeholder: None,
        },
        FieldDef {
            key: "status".into(),
            label: "Status".into(),
            field_type: "select".into(),
            group: "metadata".into(),
            editable: true,
            visible: true,
            order: 10,
            options: Some(vec![
                "RELEASING".into(),
                "FINISHED".into(),
                "NOT_YET_RELEASED".into(),
                "CANCELLED".into(),
                "HIATUS".into(),
            ]),
            placeholder: None,
        },
        FieldDef {
            key: "start_date".into(),
            label: "Start Date".into(),
            field_type: "string".into(),
            group: "metadata".into(),
            editable: true,
            visible: true,
            order: 11,
            options: None,
            placeholder: None,
        },
        FieldDef {
            key: "end_date".into(),
            label: "End Date".into(),
            field_type: "string".into(),
            group: "metadata".into(),
            editable: true,
            visible: true,
            order: 12,
            options: None,
            placeholder: None,
        },
        FieldDef {
            key: "score".into(),
            label: "Score".into(),
            field_type: "number".into(),
            group: "metadata".into(),
            editable: true,
            visible: true,
            order: 13,
            options: None,
            placeholder: None,
        },
        FieldDef {
            key: "genres".into(),
            label: "Genres".into(),
            field_type: "tags".into(),
            group: "metadata".into(),
            editable: true,
            visible: true,
            order: 14,
            options: None,
            placeholder: None,
        },
        FieldDef {
            key: "volumes".into(),
            label: "Volumes".into(),
            field_type: "number".into(),
            group: "metadata".into(),
            editable: true,
            visible: true,
            order: 15,
            options: None,
            placeholder: None,
        },
        FieldDef {
            key: "chapters".into(),
            label: "Chapters".into(),
            field_type: "number".into(),
            group: "metadata".into(),
            editable: true,
            visible: true,
            order: 16,
            options: None,
            placeholder: None,
        },
        // Status fields
        FieldDef {
            key: "note".into(),
            label: "User Rating".into(),
            field_type: "rating".into(),
            group: "status".into(),
            editable: true,
            visible: true,
            order: 20,
            options: None,
            placeholder: None,
        },
        FieldDef {
            key: "favorite".into(),
            label: "Favorite".into(),
            field_type: "boolean".into(),
            group: "status".into(),
            editable: true,
            visible: true,
            order: 21,
            options: None,
            placeholder: None,
        },
        FieldDef {
            key: "lock".into(),
            label: "Lock Metadata".into(),
            field_type: "boolean".into(),
            group: "status".into(),
            editable: true,
            visible: true,
            order: 22,
            options: None,
            placeholder: None,
        },
    ]
}

/// Returns extra fields specific to a given provider for books.
pub fn provider_book_fields(provider_id: ProviderKind) -> Vec<FieldDef> {
    match provider_id {
        ProviderKind::Marvel => vec![
            FieldDef {
                key: "urls".into(),
                label: "URLs".into(),
                field_type: "json".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 100,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "prices".into(),
                label: "Prices".into(),
                field_type: "json".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 101,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "dates".into(),
                label: "Dates".into(),
                field_type: "json".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 102,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "collected_issues".into(),
                label: "Collected Issues".into(),
                field_type: "json".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 103,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "collections".into(),
                label: "Collections".into(),
                field_type: "json".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 104,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "variants".into(),
                label: "Variants".into(),
                field_type: "json".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 105,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "series_info".into(),
                label: "Series".into(),
                field_type: "json".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 106,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "events".into(),
                label: "Events".into(),
                field_type: "json".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 107,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "stories".into(),
                label: "Stories".into(),
                field_type: "json".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 108,
                options: None,
                placeholder: None,
            },
        ],
        ProviderKind::Anilist => vec![
            FieldDef {
                key: "title_romaji".into(),
                label: "Title (Romaji)".into(),
                field_type: "string".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 100,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "title_native".into(),
                label: "Title (Native)".into(),
                field_type: "string".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 101,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "title_english".into(),
                label: "Title (English)".into(),
                field_type: "string".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 102,
                options: None,
                placeholder: None,
            },
        ],
        ProviderKind::OpenLibrary => vec![
            FieldDef {
                key: "isbn".into(),
                label: "ISBN".into(),
                field_type: "string".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 100,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "publishers".into(),
                label: "Publishers".into(),
                field_type: "tags".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 101,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "publish_date".into(),
                label: "Publish Date".into(),
                field_type: "string".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 102,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "subjects".into(),
                label: "Subjects".into(),
                field_type: "tags".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 103,
                options: None,
                placeholder: None,
            },
        ],
        ProviderKind::GoogleBooks => vec![
            FieldDef {
                key: "categories".into(),
                label: "Categories".into(),
                field_type: "tags".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 100,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "publisher".into(),
                label: "Publisher".into(),
                field_type: "string".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 101,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "published_date".into(),
                label: "Published Date".into(),
                field_type: "string".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 102,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "language".into(),
                label: "Language".into(),
                field_type: "string".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 103,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "maturity_rating".into(),
                label: "Maturity Rating".into(),
                field_type: "string".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 104,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "info_link".into(),
                label: "Info Link".into(),
                field_type: "url".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 105,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "sale_info".into(),
                label: "Sale Info".into(),
                field_type: "json".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 106,
                options: None,
                placeholder: None,
            },
        ],
        ProviderKind::MarvelUnlimited => vec![
            FieldDef {
                key: "mu_id".into(),
                label: "Marvel Unlimited ID".into(),
                field_type: "string".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 100,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "rating".into(),
                label: "Rating".into(),
                field_type: "string".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 101,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "upc".into(),
                label: "UPC".into(),
                field_type: "string".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 102,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "price".into(),
                label: "Price".into(),
                field_type: "string".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 103,
                options: None,
                placeholder: None,
            },
        ],
        ProviderKind::Metron => vec![
            FieldDef {
                key: "series_name".into(),
                label: "Series Name".into(),
                field_type: "string".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 100,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "cover_date".into(),
                label: "Cover Date".into(),
                field_type: "string".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 101,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "store_date".into(),
                label: "Store Date".into(),
                field_type: "string".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 102,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "price".into(),
                label: "Price".into(),
                field_type: "string".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 103,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "sku".into(),
                label: "SKU".into(),
                field_type: "string".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 104,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "upc".into(),
                label: "UPC".into(),
                field_type: "string".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 105,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "isbn".into(),
                label: "ISBN".into(),
                field_type: "string".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 106,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "arcs".into(),
                label: "Story Arcs".into(),
                field_type: "json".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 107,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "reprints".into(),
                label: "Reprints".into(),
                field_type: "json".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 108,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "resource_url".into(),
                label: "Metron URL".into(),
                field_type: "url".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 109,
                options: None,
                placeholder: None,
            },
        ],
        _ => vec![],
    }
}

/// Returns extra fields specific to a given provider for series.
pub fn provider_series_fields(provider_id: ProviderKind) -> Vec<FieldDef> {
    match provider_id {
        ProviderKind::Marvel => vec![FieldDef {
            key: "urls".into(),
            label: "URLs".into(),
            field_type: "json".into(),
            group: "api_specific".into(),
            editable: false,
            visible: true,
            order: 100,
            options: None,
            placeholder: None,
        }],
        ProviderKind::Anilist => vec![
            FieldDef {
                key: "title_romaji".into(),
                label: "Title (Romaji)".into(),
                field_type: "string".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 100,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "title_native".into(),
                label: "Title (Native)".into(),
                field_type: "string".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 101,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "title_english".into(),
                label: "Title (English)".into(),
                field_type: "string".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 102,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "trending".into(),
                label: "Trending".into(),
                field_type: "number".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 103,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "source".into(),
                label: "Source".into(),
                field_type: "string".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 104,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "relations".into(),
                label: "Relations".into(),
                field_type: "json".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 105,
                options: None,
                placeholder: None,
            },
        ],
        ProviderKind::Metron => vec![
            FieldDef {
                key: "year_began".into(),
                label: "Year Began".into(),
                field_type: "number".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 100,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "year_end".into(),
                label: "Year End".into(),
                field_type: "number".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 101,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "issue_count".into(),
                label: "Issue Count".into(),
                field_type: "number".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 102,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "series_type".into(),
                label: "Series Type".into(),
                field_type: "string".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 103,
                options: None,
                placeholder: None,
            },
            FieldDef {
                key: "resource_url".into(),
                label: "Metron URL".into(),
                field_type: "url".into(),
                group: "api_specific".into(),
                editable: false,
                visible: true,
                order: 104,
                options: None,
                placeholder: None,
            },
        ],
        _ => vec![],
    }
}

/// Build the full field schema for a provider + item type.
pub fn build_field_schema(
    provider_id: ProviderKind,
    provider_name: &str,
    item_type: &str,
) -> FieldSchema {
    let common = match item_type {
        "book" => common_book_fields(),
        "series" => common_series_fields(),
        _ => vec![],
    };
    let specific = match item_type {
        "book" => provider_book_fields(provider_id),
        "series" => provider_series_fields(provider_id),
        _ => vec![],
    };

    let mut fields = common;
    fields.extend(specific);

    FieldSchema {
        provider_id,
        provider_name: provider_name.to_string(),
        item_type: item_type.to_string(),
        fields,
    }
}
