pub mod auth;
pub mod db;
pub mod download;
pub mod latest;
pub mod models;
pub mod search;

// Re-export public types and Tauri commands so lib.rs paths remain unchanged.
// Glob re-exports also forward the hidden __cmd__* items generated by #[tauri::command].
pub use auth::*;
pub use db::*;
pub use download::*;
pub use latest::*;
#[allow(unused_imports)]
pub use models::*;
pub use search::*;

// ── Shared browser infrastructure ────────────────────────

use headless_chrome::Browser;
use once_cell::sync::Lazy;
use scraper::{Html, Selector};
use std::collections::HashMap;
use std::sync::Mutex;
use std::time::Duration;

/// Global persistent headless browser for VIZ Media scraping.
static VIZ_PERSISTENT_BROWSER: Lazy<Mutex<Option<Browser>>> = Lazy::new(|| Mutex::new(None));

/// Get or launch the persistent browser for VIZ Media.
pub(crate) fn get_viz_persistent_browser(
) -> Result<std::sync::MutexGuard<'static, Option<Browser>>, String> {
    let mut guard = VIZ_PERSISTENT_BROWSER
        .lock()
        .map_err(|e| format!("VIZ browser mutex poisoned: {:?}", e))?;
    if guard.is_none() {
        let mut options = headless_chrome::LaunchOptionsBuilder::default()
            .headless(true)
            .idle_browser_timeout(Duration::from_secs(600))
            .build()
            .map_err(|e| format!("Failed to build launch options: {}", e))?;

        options.args.push(std::ffi::OsStr::new(
            "--disable-blink-features=AutomationControlled",
        ));

        let browser =
            Browser::new(options).map_err(|e| format!("Failed to launch browser: {}", e))?;
        *guard = Some(browser);
    }
    Ok(guard)
}

/// Render a VIZ Media page with cookie injection and return HTML.
pub(crate) fn render_viz_page_with_cookies(
    url: &str,
    cookies: &HashMap<String, String>,
    wait_selector: &str,
) -> Result<String, String> {
    let guard = get_viz_persistent_browser()?;
    let browser_ref = guard
        .as_ref()
        .ok_or_else(|| "VIZ Browser was not initialized".to_string())?;
    let tab = browser_ref
        .new_tab()
        .map_err(|e| format!("Failed to open new tab: {}", e))?;

    if let Err(e) = tab.enable_stealth_mode() {
        tracing::warn!("Failed to enable stealth mode: {:?}", e);
    }

    if let Err(_e) =
        tab.call_method(headless_chrome::protocol::cdp::Network::ClearBrowserCookies { 0: None })
    {
    }

    if !cookies.is_empty() {
        tracing::debug!("Setting {} cookies via CDP for VIZ Media", cookies.len());

        let viz_essential_names: &[&str] = &["_session_id", "vid"];

        for (name, value) in cookies.iter() {
            let name_lower = name.to_lowercase();
            if !viz_essential_names.iter().any(|&n| name_lower == n) {
                tracing::debug!("Skipping non-essential cookie: {}", name);
                continue;
            }

            if let Err(e) = tab.call_method(headless_chrome::protocol::cdp::Network::SetCookie {
                name: name.to_string(),
                value: value.to_string(),
                url: None,
                domain: Some(".viz.com".to_string()),
                path: Some("/".to_string()),
                secure: Some(true),
                http_only: Some(false),
                same_site: Some(headless_chrome::protocol::cdp::Network::CookieSameSite::Lax),
                expires: None,
                priority: None,
                same_party: None,
                source_scheme: None,
                source_port: None,
                partition_key: None,
            }) {
                tracing::warn!("Failed to set VIZ cookie {} via CDP: {:?}", name, e);
            }
        }
        std::thread::sleep(Duration::from_millis(100));
    }

    tab.navigate_to(url)
        .map_err(|e| format!("Failed to navigate to {}: {}", url, e))?;

    let _ = tab.wait_for_element(wait_selector);

    let scroll_script = r#"
        (function() {
            window.scrollTo(0, document.body.scrollHeight);
            setTimeout(() => window.scrollTo(0, 0), 300);
        })();
    "#;
    let _ = tab.evaluate(scroll_script, false);

    std::thread::sleep(Duration::from_millis(3000));

    let content = tab
        .get_content()
        .map_err(|e| format!("Failed to capture rendered content: {}", e))?;

    if let Err(e) = tab.close(true) {
        tracing::warn!("Failed to close VIZ tab: {:?}", e);
    }

    Ok(content)
}

/// Extract chapter ID from VIZ URLs like `/shonenjump/{slug}-chapter-{num}/chapter/{id}`
pub(crate) fn extract_viz_chapter_id(url: &str) -> String {
    if let Some(captures) = regex::Regex::new(r"/chapter/(\d+)")
        .ok()
        .and_then(|re| re.captures(url))
    {
        if let Some(id) = captures.get(1) {
            return id.as_str().to_string();
        }
    }
    String::new()
}

/// Extract chapter number from title like "Chapter 420" or from URL
pub(crate) fn extract_viz_chapter_number(title: &str) -> String {
    if let Some(captures) = regex::Regex::new(r"(?i)ch(?:apter)?\.?\s*(\d+(?:\.\d+)?)")
        .ok()
        .and_then(|re| re.captures(title))
    {
        if let Some(num) = captures.get(1) {
            return num.as_str().to_string();
        }
    }
    if let Some(captures) = regex::Regex::new(r"#(\d+)")
        .ok()
        .and_then(|re| re.captures(title))
    {
        if let Some(num) = captures.get(1) {
            return num.as_str().to_string();
        }
    }
    String::new()
}

/// Convert a VIZ slug like `one-piece` to a readable title `One Piece`
pub(crate) fn series_slug_to_title(slug: &str) -> String {
    slug.split('-')
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().to_string() + c.as_str(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

/// Parse a VIZ chapters listing page and extract chapter entries.
pub(crate) fn parse_viz_chapters_page(html: &str, series_slug: &str) -> Vec<models::VizChapter> {
    let document = Html::parse_document(html);
    let mut chapters = Vec::new();

    let free_link_sel = Selector::parse("a[href*='/chapter/']").unwrap();
    for link in document.select(&free_link_sel) {
        let href = link.value().attr("href").unwrap_or("");
        let chapter_id = extract_viz_chapter_id(href);
        if chapter_id.is_empty() {
            continue;
        }

        let text = link.text().collect::<String>();
        let text = text.trim();

        let chapter_number = extract_viz_chapter_number(text);
        let is_free = text.contains("FREE");

        let title = if !chapter_number.is_empty() {
            format!(
                "{} Chapter {}",
                series_slug_to_title(series_slug),
                chapter_number
            )
        } else {
            text.to_string()
        };

        let series_title = document
            .select(&Selector::parse("h2").unwrap())
            .next()
            .map(|el| el.text().collect::<String>().trim().to_string());

        let date_re = regex::Regex::new(
            r"(?i)(January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{1,2},?\s*\d{4}",
        )
        .ok();
        let publish_date = date_re.and_then(|re| re.find(text).map(|m| m.as_str().to_string()));

        if chapters
            .iter()
            .any(|c: &models::VizChapter| c.id == chapter_id)
        {
            continue;
        }

        chapters.push(models::VizChapter {
            id: chapter_id,
            title,
            chapter_number,
            description: String::new(),
            cover_url: String::new(),
            series_id: Some(series_slug.to_string()),
            series_title,
            creators: None,
            publish_date,
            page_count: None,
            subscription: Some("shonenjump".to_string()),
            free: Some(is_free),
        });
    }

    let ch_num_re = regex::Regex::new(r"Ch\.\s*(\d+(?:\.\d+)?)").unwrap();

    if let Ok(row_sel) = Selector::parse("tr, [class*='chapter-table'] a, [class*='_table'] a") {
        for row in document.select(&row_sel) {
            let row_text = row.text().collect::<String>();
            let row_text = row_text.trim();

            if let Some(caps) = ch_num_re.captures(row_text) {
                if let Some(num_match) = caps.get(1) {
                    let chapter_number = num_match.as_str().to_string();
                    let is_free = row_text.contains("FREE");

                    let href = row
                        .select(&Selector::parse("a[href*='/chapter/']").unwrap())
                        .next()
                        .and_then(|a| a.value().attr("href"));

                    let chapter_id = if let Some(href) = href {
                        let id = extract_viz_chapter_id(href);
                        if id.is_empty() {
                            format!("viz_{}_{}", series_slug, chapter_number)
                        } else {
                            id
                        }
                    } else {
                        format!("viz_{}_{}", series_slug, chapter_number)
                    };

                    if chapters
                        .iter()
                        .any(|c: &models::VizChapter| c.id == chapter_id)
                    {
                        continue;
                    }
                    if chapters
                        .iter()
                        .any(|c: &VizChapter| c.chapter_number == chapter_number)
                    {
                        continue;
                    }

                    let title = format!(
                        "{} Chapter {}",
                        series_slug_to_title(series_slug),
                        chapter_number
                    );

                    let series_title = document
                        .select(&Selector::parse("h2").unwrap())
                        .next()
                        .map(|el| el.text().collect::<String>().trim().to_string());

                    chapters.push(VizChapter {
                        id: chapter_id,
                        title,
                        chapter_number,
                        description: String::new(),
                        cover_url: String::new(),
                        series_id: Some(series_slug.to_string()),
                        series_title,
                        creators: None,
                        publish_date: None,
                        page_count: None,
                        subscription: Some("shonenjump".to_string()),
                        free: Some(is_free),
                    });
                }
            }
        }
    }

    chapters.sort_by(|a, b| {
        let a_num: f64 = a.chapter_number.parse().unwrap_or(0.0);
        let b_num: f64 = b.chapter_number.parse().unwrap_or(0.0);
        b_num
            .partial_cmp(&a_num)
            .unwrap_or(std::cmp::Ordering::Equal)
    });

    chapters
}
