name: cosmiccomics
base: core24
version: '3.0.0'
summary: Read Comics, Manga and Ebooks the easy way
description: |
  Cosmic Comics offers a user-friendly interface that makes it easy to browse the collection of comics, manga and ebooks. It supports different file formats, offers adaptive page layout, favorite page marking, advanced search and library management.

grade: stable
confinement: strict

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1

apps:
  cosmiccomics:
    command: usr/bin/cosmiccomics
    desktop: usr/share/applications/fr.nytuo.cosmiccomics.desktop
    extensions: [gnome]
    plugs:
      - network
      - home
      - removable-media

parts:
  build-app:
    plugin: dump
    build-snaps:
      - node/20/stable
      - rustup/latest/stable
    build-packages:
      - libwebkit2gtk-4.1-dev
      - build-essential
      - curl
      - wget
      - file
      - libxdo-dev
      - libssl-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - dpkg
      - clang
      - libclang-dev
      - llvm-dev
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
    source: .
    override-build: |
      set -eu
      rustup default stable
      export LIBCLANG_PATH=/usr/lib/llvm-18/lib
      export CLANG_PATH=/usr/bin/clang-18
      npm install
      npm run tauri build -- --bundles deb -- --no-default-features
      dpkg -x src-tauri/target/release/bundle/deb/*.deb $SNAPCRAFT_PART_INSTALL/
      sed -i -e "s|Icon=appname|Icon=/usr/share/icons/hicolor/32x32/apps/cosmiccomics.png|g" $SNAPCRAFT_PART_INSTALL/usr/share/applications/fr.nytuo.cosmiccomics.desktop