name: Build/release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
jobs:
  release_linux_win:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.2.0

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Get Package Version
        uses: nyaa8/package-version@v1
        with:
          path: 'package.json'
          
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
      - name: Building the Project
        working-directory: ./
        run: |
            sudo dpkg --add-architecture i386
            sudo apt update
            sudo apt install wine64
            sudo apt install wine32
            
            yarn install
            yarn devBuild
            yarn electron-builder --win -p never
        env:
          PKGVER: v${{env.PACKAGE_VERSION}}
      
      - name: Publishing...
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: ${{env.PKGVER}}
          files: |
            ${{github.workspace}}/dist/*.zip
            ${{github.workspace}}/dist/*.snap
            ${{github.workspace}}/dist/*.exe
            ${{github.workspace}}/dist/*.blockmap
            ${{github.workspace}}/dist/latest.yml
            ${{github.workspace}}/dist/*.deb
            ${{github.workspace}}/dist/*.AppImage
            ${{github.workspace}}/dist/*.rpm
            ${{github.workspace}}/dist/latest-linux.yml
            ${{github.workspace}}/dist/latest-linux-arm64.yml
            ${{github.workspace}}/dist/latest-linux-ia32.yml
        env:
          PKGVER: v${{env.PACKAGE_VERSION}}
          
  PushVersion:
    needs: release_linux_win
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.2.0
      with:
        fetch-depth: 0
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"

    - name: 'Writting'
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: ${{ github.workspace}}/Version.txt
        contents: |
          ${{ steps.previoustag.outputs.tag }}
        write-mode: overwrite
    - name: push
      uses: github-actions-x/commit@v2.8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'Automated Version Update'
        force-add: 'true'
        name: JARVIS [BOT]
        email: nytuo.yt@gmail.com
